export const WORD_MAP = {
  wdrazamy: "wdrażamy", wdrazany: "wdrażany", wdrazane: "wdrażane",
  wdrazana: "wdrażana", wdrazanie: "wdrażanie", wdrazajac: "wdrażając",
  wdrozenie: "wdrożenie", wdrozenia: "wdrożenia", wdrozen: "wdrożeń",
  wdrozeniu: "wdrożeniu", wdrozeniach: "wdrożeniach",
  urzadzenie: "urządzenie", urzadzenia: "urządzenia", urzadzen: "urządzeń",
  urzadzeniu: "urządzeniu", urzadzeniem: "urządzeniem",
  ktore: "które", ktorej: "której", ktory: "który", ktora: "która",
  ktorych: "których", ktorym: "którym", ktorzy: "którzy", ktos: "ktoś",
  mozliwosc: "możliwość", mozliwosci: "możliwości", mozliwe: "możliwe",
  moze: "może", mozna: "można",
  wielkosc: "wielkość", wielkosci: "wielkości",
  bezpieczenstwo: "bezpieczeństwo", bezpieczenstwa: "bezpieczeństwa",
  obsluga: "obsługa", obslugi: "obsługi", obsluge: "obsługę",
  obslugujemy: "obsługujemy",
  przesylek: "przesyłek", przesylki: "przesyłki", przesylka: "przesyłka",
  przesylanych: "przesyłanych", przesylane: "przesyłane",
  sluzb: "służb", sluzby: "służby",
  sprzedazy: "sprzedaży", sprzedaz: "sprzedaż",
  zamowien: "zamówień", zamowienia: "zamówienia", zamowieniami: "zamówieniami",
  zamowieniach: "zamówieniach", zamowienie: "zamówienie",
  branzy: "branży", branza: "branża", branze: "branże",
  modulow: "modułów", modulu: "modułu", moduly: "moduły", modul: "moduł",
  modulami: "modułami", modulem: "modułem", modularny: "modularny",
  zabudow: "zabudów", zabudowy: "zabudowy", zabudowa: "zabudowa",
  glownej: "głównej", glowna: "główna", glowny: "główny", glownie: "głównie",
  glowne: "główne", glownego: "głównego",
  najwiekszych: "największych", najwiekszymi: "największymi",
  najwiekszy: "największy", najwieksze: "największe", najwieksza: "największa",
  wiekszy: "większy", wieksza: "większa", wieksze: "większe",
  zwieksza: "zwiększa", zwiekszenie: "zwiększenie", zwiekszajac: "zwiększając",
  zwiekszyc: "zwiększyć",
  skrocenie: "skrócenie", skroceniu: "skróceniu", skrocenia: "skrócenia",
  krotsze: "krótsze", krotszy: "krótszy", krotka: "krótka", krotko: "krótko",
  elastycznosc: "elastyczność", elastyczna: "elastyczna",
  zgodnosc: "zgodność", trwalosc: "trwałość", stabilnosc: "stabilność",
  latwosc: "łatwość", latwy: "łatwy", latwe: "łatwe", latwo: "łatwo",
  latwa: "łatwa", latwiejszy: "łatwiejszy",
  modularnosc: "modularność", skalowalnosc: "skalowalność",
  uniwersalnosc: "uniwersalność", wydajnosc: "wydajność",
  skalowalna: "skalowalną", skalowalne: "skalowalne",
  odbior: "odbiór", odbioru: "odbioru",
  ponizej: "poniżej", powyzej: "powyżej",
  calej: "całej", calym: "całym", cala: "cała", caly: "cały", cale: "całe",
  oczekiwan: "oczekiwań", oczekiwania: "oczekiwania",
  usunieta: "usunięta", usuniety: "usunięty", usuniete: "usunięte",
  niewlasciwy: "niewłaściwy", niewlasciwa: "niewłaściwa",
  sprawdz: "sprawdź", wroc: "wróć", wrocic: "wrócić",
  rozwoj: "rozwój", rozwoju: "rozwoju",
  zapewniajace: "zapewniające", zapewniajacy: "zapewniający",
  zapewniajaca: "zapewniająca", zapewniajacych: "zapewniających",
  umozliwiajace: "umożliwiające", umozliwia: "umożliwia",
  umozliwiajacy: "umożliwiający",
  wlasny: "własny", wlasna: "własna", wlasne: "własne", wlasnie: "właśnie",
  modulowy: "modułowy", modulowa: "modułowa", modulowe: "modułowe",
  otworz: "otwórz", wyslij: "wyślij",
  wiadomosc: "wiadomość", wiadomosci: "wiadomości",
  imie: "imię", powieksz: "powiększ",
  nastepne: "następne", nastepna: "następna", nastepny: "następny",
  nastepnie: "następnie",
  dziekujemy: "dziękujemy", wysylanie: "wysyłanie",
  wyslana: "wysłana", wyslane: "wysłane", wyslano: "wysłano",
  zostala: "została", zostal: "został", zostalo: "zostało", zostaly: "zostały",
  poszlo: "poszło", sprobuj: "spróbuj",
  posrednictwa: "pośrednictwa", posrednictwo: "pośrednictwo",
  wylaczenie: "wyłączenie", wlaczenie: "włączenie", wlaczajac: "włączając",
  zagrozenia: "zagrożenia", zagrozenie: "zagrożenie",
  miedzy: "między", pelnym: "pełnym", pelny: "pełny", pelna: "pełna",
  pelne: "pełne", pelnym: "pełnym",
  szczegolow: "szczegółów", szczegoly: "szczegóły",
  paczke: "paczkę", paczki: "paczki",
  przestrzen: "przestrzeń", marke: "markę", obudowe: "obudowę",
  grafike: "grafikę", liczbe: "liczbę",
  dazymy: "dążymy", dazy: "dąży",
  sie: "się", tez: "też", juz: "już", wiec: "więc",
  rowniez: "również", roznych: "różnych", roznymi: "różnymi",
  rozne: "różne", rozny: "różny", rozna: "różna", roznica: "różnica",
  duzym: "dużym", duza: "duża", duze: "duże", duzo: "dużo",
  wlasciwy: "właściwy", wlasciwie: "właściwie",
  najblizsze: "najbliższe", najblizszy: "najbliższy", blisko: "blisko",
  upewnienie: "upewnienie", upewnic: "upewnić",
  rozwiazania: "rozwiązania", rozwiazaniem: "rozwiązaniem",
  rozwiazan: "rozwiązań",
  wspolpracujemy: "współpracujemy", wspolpraca: "współpraca",
  wspolpracy: "współpracy",
  bezpieczna: "bezpieczna", bezpieczny: "bezpieczny",
  efektowna: "efektowna",
};

export function makeReplacer(skip = new Set()) {
  const entries = Object.entries(WORD_MAP).filter(([a]) => !skip.has(a));
  entries.sort((a, b) => b[0].length - a[0].length);
  const res = entries.map(([a, p]) => [new RegExp("\\b" + a + "\\b", "gi"), p]);
  return (text) => {
    let o = text;
    for (const [re, p] of res) o = o.replace(re, (mm) => (mm[0] !== mm[0].toLowerCase() ? p[0].toUpperCase() + p.slice(1) : p));
    return o;
  };
}

export const fixString = (s) =>
  s.replace(/[\u2014\u2013]/g, "-").replace(/15 sekund/g, "10 sekund").replace(/15 seconds/g, "10 seconds").replace(/15 s\b/g, "10 s");
